api/public/swagger.yaml
api/src/app.ts
api/src/controllers/drive.ts
api/src/routes/api/drive.ts

fix: increased req body size

---

api/package-lock.json
api/package.json
api/src/app.ts
api/src/middlewares/authenticateToken.ts
api/src/routes/web/index.ts
api/src/routes/web/web.ts
web/src/components/login.tsx
web/src/context/appContext.tsx

Session based authentication is already implemented.
Web apps need to access APIs without access token and utilise their valid session.
Access is granted to secured APIs if session is valid.
Need to add CSRF protection to all requests trying to access API with valid session.
- Added CSRF protection to authenticateAccessToken
- Added CSRF protection to all web routes
- Setting CSRF Token upon SPA render only

fix: added CSRF check for granting access via session authentication

---

api/package-lock.json
api/package.json
api/public/swagger.yaml
api/src/controllers/web.ts
api/src/routes/api/index.ts
api/src/routes/web/web.ts

Cookie Authentication on Swagger UI is not supported
> Note for Swagger UI and Swagger Editor users: Cookie authentication is currently not supported for "try it out" requests due to browser security restrictions. See [this issue](https://github.com/swagger-api/swagger-js/issues/1163) for more information. [SwaggerHub](https://swagger.io/tools/swaggerhub/) does not have this limitation.
Ref: https://swagger.io/docs/specification/authentication/cookie-authentication/
Implemented request intercepter to manually add CSRF in headers.

fix: consume swagger api with CSRF

---

README.md
api/csp.config.example.json
api/src/utils/parseHelmetConfig.ts

Temporarily loosening CSP Policy to allow seamless DC deploys.
Currently DC contains the bare minimum number of frontend files, to facilitate streaming apps on SAS 9 EBI deploys (many of which have only 3 multibridge connections).  Multiple parallel file requests can also bring down a Viya 4 image (2020.2 hackathon image confirmed).
That said - inline javascript is bad as it can facilitate Cross Site Scripting (XSS) attacks.  More info here:  https://csper.io/blog/no-more-unsafe-inline
The SASjs Server build of Data Controller will be updated to eliminate the script tags and then the CSP policy will be tightened up.  Ticket to follow.

fix: csp updates

---

api/src/controllers/internal/Session.ts

There appears to be no reliable way to enforce UTF-8 without additional modifications to the PATH variable to ensure a DBCS instance of SAS.
Closes #205

fix: removing UTF-8 options from commandline.

---

api/src/utils/getRunTimeAndFilePath.ts

none
* getRuntimeAndFilePath function to handle the scenario when the path is provided with an extension other than runtimes
* add an additional check to see if the extension belongs to `RunTimeType`

fix: getRuntimeAndFilePath function

---

api/src/utils/zipped.ts

Closes #211 
rather than insist on a file with the same name as the zip, we should just check that the content is a single, valid, json file
Extracting first json file present in zip file.

fix(deploy): extract first json from zip file

---

README.md
api/.env.example
api/public/swagger.yaml
api/src/app.ts
api/src/controllers/auth.ts
api/src/controllers/group.ts
api/src/middlewares/authenticateToken.ts
api/src/model/Configuration.ts
api/src/model/Group.ts
api/src/model/User.ts
api/src/types/system/process.d.ts
api/src/utils/connectDB.ts
api/src/utils/generateAccessToken.ts
api/src/utils/generateAuthCode.ts
api/src/utils/generateRefreshToken.ts
api/src/utils/getRunTimeAndFilePath.ts
api/src/utils/seedDB.ts
api/src/utils/setProcessVariables.ts
api/src/utils/verifyEnvVariables.ts

Closes #213 
All the secrets should be saved in DB, auto-generated and if already present, load them on server start.
Moved `ACCESS_TOKEN_SECRET`, `REFRESH_TOKEN_SECRET`, `AUTH_CODE_SECRET`, `SESSION_SECRET` from `process.env` to `process.secrets`
On startup: 
- loaded from DB
- if not present, generated and saved to DB
- then set to process.secrets
Updated `seedDB.ts` accordingly

feat: removed secrets from env variables

---

api/src/controllers/internal/Session.ts

Closes #229
#229 
Ensuring NOSPLASH is only applied where it is supported
Testing the end of the SAS_PATH string for `sas.exe`

fix: ensuring nosplash option only applies for sas.exe

---

web/src/components/filePathInputModal.tsx
web/src/components/nameInputModal.tsx
web/src/components/tree.tsx
web/src/containers/Studio/editor.tsx
web/src/utils/hooks/index.ts
web/src/utils/hooks/usePrompt.ts
web/src/utils/hooks/useStateWithCallback.ts

* do not show unsaved changes prompt when doing save as
* when no file is selected show load content into editor from local storage
* fixed selected tab indicator in case of webout tab
* add custom useStateWithCallback hook
* add useEffect for updating file content in local storage
* moved Tooltip inside label of webout tab instead of wrapping tab with tooltip

fix: issues fixed in studio page

---

api/public/swagger.yaml
api/src/controllers/info.ts
api/src/controllers/permission.ts
api/src/middlewares/authorize.ts
api/src/model/Permission.ts
api/src/routes/api/permission.ts
api/src/routes/api/spec/drive.spec.ts
api/src/routes/api/spec/permission.spec.ts
api/src/routes/api/spec/stp.spec.ts
api/src/utils/getAuthorizedRoutes.ts
api/src/utils/validation.ts
web/src/containers/Settings/addPermissionModal.tsx
web/src/containers/Settings/index.tsx
web/src/containers/Settings/permission.tsx
web/src/containers/Settings/permissionFilterModal.tsx
web/src/utils/types.ts

closes #241 
* if user is admin, return all permission in response of  `SASjsApi/permission` else return user's permissions only
* update permission modal schema such that it should have path attribute instead of uri and add an additional attribute for permission type

fix: show non-admin user his own permissions only

---

api/src/app.ts
api/src/routes/api/spec/web.spec.ts
api/src/routes/appStream/style.ts
api/src/routes/web/web.ts
api/src/utils/verifyEnvVariables.ts
web/src/App.tsx
web/src/context/appContext.tsx

Applications needs to be authenticated with API server on different domain.
And fixes #125, #242 
Cookie based authentication should work along CSRF protection.
Instead of sending CSRF Token from server via cookie, now it will be provided in head section.
Any request which was meant to get CSRF token, should process response extract CSRF token and save in cookie involves

fix(cookie): XSRF cookie is removed and passed token in head section

---

web/src/components/header.tsx
web/src/components/username.tsx
web/src/containers/Settings/addPermissionModal.tsx
web/src/containers/Settings/addPermissionResponseModal.tsx
web/src/containers/Settings/index.tsx
web/src/containers/Settings/permission.tsx
web/src/containers/Settings/permissionFilterModal.tsx
web/src/containers/Studio/editor.tsx
web/src/containers/Studio/sideBar.tsx
web/src/utils/helper.ts

closes #225 
* add multiple permissions at once using UI
* make Path input filed multi-select
* make a request to API for each path
* add a new modal to show added permissions and error responses

feat: add multiple permission for same combination of type and principal at once

---

api/src/controllers/internal/createSASProgram.ts

#253
Enable proc print output
Added the following SAS code at the start of each invocation:
```sas
proc printto print="%sysfunc(getoption(log))";
run;
```

fix: adding proc printto in precode to enable print output in log.  Closes #253

---

api/src/controllers/code.ts
api/src/controllers/internal/Execution.ts
api/src/controllers/stp.ts
api/src/routes/api/stp.ts
api/src/types/system/process.d.ts
api/src/utils/setProcessVariables.ts
web/src/containers/Studio/editor.tsx

closes #258
* Send back the raw value of webout.txt directly in the response
* Append the log if DEBUG >0 or if the executable returned a non-0 response
* Use a separator to distinguish the two in the response
* modified stp controller to handle the updated response from execution controller
* modified code controller to handle the updated response from execution controller
* add new process variable: `process.logsUUID = 'SASJS_LOGS_SEPARATOR_163ee17b6ff24f028928972d80a26784'`

fix: update response of /SASjsApi/stp/execute and /SASjsApi/code/execute

---

web/src/components/filePathInputModal.tsx
web/src/components/nameInputModal.tsx
web/src/containers/Studio/editor.tsx

closes #256 
* allow underscores in file names
* when no file is selected `ctrl + s` should open a file name input modal
* when a file is selected and prev file content is not equal to current file content, `ctrl + s` should save updated file
* add an action to editor instance

feat: add the functionality of saving file by ctrl + s in editor

---

api/src/utils/getDesktopFields.ts

closes #265
* If python is not set as a runtime, it should not ask for PYTHON_PATH on launch
* it was a typo mistake, should have `PY` instead of `JS`

fix: typo mistake

---

api/src/controllers/internal/Session.ts

#260 
Initial SAS folder should be the session folder, similar to Python and JS Stored Programs.
Used SASINITIALFOLDER startup option.

fix: addition of SASINITIALFOLDER startup option.  Closes #260

---

api/src/controllers/internal/Session.ts

#267 
Make SASINITIALFOLDER windows only
Test to see if SAS executable ends with ".exe" and if so, use the option

fix: making SASINITIALFOLDER option windows only.  Closes #267

---

api/src/controllers/internal/Session.ts

#271 
Fix missing param value
split params over 2 entries

fix: SASINITIALFOLDER split over 2 params, closes #271

---

api/package-lock.json
api/package.json
api/src/controllers/internal/createJSProgram.ts
api/src/controllers/internal/createPythonProgram.ts
api/src/controllers/internal/createRProgram.ts
api/src/controllers/internal/createSASProgram.ts
api/src/controllers/internal/processProgram.ts

closes #281
* variable `SASJS_WEBOUT_HEADERS` should have double backslash instead of single in case of windows

fix: SASJS_WEBOUT_HEADERS path for windows

---

api/src/controllers/internal/Session.ts

* default content-type for sas session should be `text/plain`
* create a headers file at the time of session creation for sas runtime.

fix: default content-type for sas programs should be text/plain

---

web/src/containers/Studio/internal/helper.ts

n/a
Removing single quotes from mac var value (_program)
Removed 2 single quotes

fix: removing single quotes from _program value

---

api/src/utils/getRunTimeAndFilePath.ts
web/src/containers/Studio/internal/hooks/useEditor.ts

closes #288 
* make file extensions case insensitive in studio
* convert provided file extension to lower case and then check against available runtimes

fix: made files extensions case insensitive

---

api/.env.example
api/src/app-modules/configureExpressSession.ts
api/src/app.ts
api/src/routes/web/web.ts
api/src/utils/verifyEnvVariables.ts

Closes #299
Need to have shared session cookies, to serve AppStream hosted on separate domain.
Added domain to cookies

fix: added domain for session cookies

---

web/src/components/deleteConfirmationModal.tsx
web/src/components/nameInputModal.tsx
web/src/components/tree.tsx
web/src/containers/Studio/sideBar.tsx

* mui TreeView is much more interactive than custom implementations
* previously, there was an [issue](https://stackoverflow.com/questions/73085457/material-ui-treeview-unexpectedly-toggles-node-when-context-menu-item-is-clicked) with mui TreeView that could not be solved at that time but now fixed with `event.stopPropagation`

fix(web): use mui treeView instead of custom implementation

---

api/package-lock.json
api/public/swagger.yaml
api/src/controllers/auth.ts
api/src/controllers/client.ts
api/src/model/Client.ts
api/src/utils/generateAccessToken.ts
api/src/utils/generateRefreshToken.ts
api/src/utils/validation.ts
web/src/containers/Studio/internal/hooks/useEditor.ts

closes #307
* Currently, the access token is hard-coded to 1 day. The intent of this PR is to make it configurable when creating a client.
* add a new property in `accessTokenExpiryDays` to the Client modal which will be used in setting the expiry of the access token.

feat: make access token duration configurable when creating client

---

api/src/controllers/internal/Execution.ts
api/src/controllers/internal/Session.ts
api/src/controllers/stp.ts

closes #322 
update default response headers as:
* no-debug -> content-type: text/html; charset=utf-8
* debug -> content-type: text/plain
* updated default header when creating session to `content-type: text/html; charset=utf-8`
* if debug is true  update to `content-type: text/plain`
* previously we weren't setting the response header. Now set response headers returned from execution controller

fix: update the response header of request to stp/execute routes

---

api/src/controllers/internal/Session.ts
api/src/controllers/internal/processProgram.ts
api/src/types/system/process.d.ts

closes #326
closes #328
* JS / Python / R session folders should be NEW folders, not existing SAS folders
* use `childProcess.execFile` instead of `execFileSync`.
* introduced a new process variable to hold sas session controller

fix: non sas programs shouldn't use sas session folder

---

web/src/containers/Studio/internal/hooks/useEditor.ts

closes #331
* when API sends a JSON file in response, It's treated as a JSON object on the frontend. So, stringify the response data before setting it to file content.

fix: stringify json file

---

api/src/middlewares/authorize.ts
api/src/utils/getAuthorizedRoutes.ts

closes #224
Enable the `/SASjsApi` top-level endpoint to a particular user/group. This would enable all the (configurable) APIs below it. If an admin GRANT access to say, `/AppStream`, it should grant for all (unless a specific one is DENIED)

feat: Add /SASjsApi endpoint in permissions

---

README.md
api/.env.example
api/src/app-modules/configureExpressSession.ts
api/src/utils/verifyEnvVariables.ts

closes #399
* fix: when using  Microsoft azure's cosmos MongoDB, it throws an error on configuring express session
* added a new env variable DB_TYPE that is checked before creating a MongoStore for storing sessions.

feat: add new env config DB_TYPE

---

README.md
api/.env.example
api/src/utils/seedDB.ts
api/src/utils/verifyEnvVariables.ts

closes #348
* add the option to reset admin password on app restart
* make initial admin username and password configurable
* introduced 3 new env variables for configuration of initial admin user

feat: option to reset admin password on startup

---

api/src/controllers/internal/Session.ts

Closes #352
Apply -nologo option only for sas.exe executable
Tested SAS_PATH for 'sas.exe' to make option apply only in this case

fix: applying nologo only for sas.exe

---

README.md
api/src/routes/api/spec/web.spec.ts
api/src/utils/rateLimiter.ts

animir/node-rate-limiter-flexible#206
Using Microsoft Azure's CosmosDB for MongoDB is breaking the server due to some issues in `RateLimiterMongo` from `node-rate-limiter-flexible`. So, replaced `RateLimiterMongo` with `RateLimiterMemory`.

fix: use RateLimiterMemory instead of RateLimiterMongo

---

web/package-lock.json
web/package.json
web/src/containers/Settings/internal/hooks/useAddPermission.tsx
web/src/containers/Studio/editor.tsx
web/src/containers/Studio/internal/components/log/log.module.css
web/src/containers/Studio/internal/components/log/logChunk.tsx
web/src/containers/Studio/internal/components/log/logComponent.tsx
web/src/containers/Studio/internal/components/log/logTabWithIcons.tsx
web/src/containers/Studio/internal/hooks/useEditor.ts
web/src/types/declaration.d.ts
web/src/utils/index.ts
web/src/utils/log.ts
web/src/utils/types.ts
web/tsconfig.json
web/webpack.common.ts

Closes #346 
- Display error and warning icons in `Log` tab if the runtime is `SAS`.
- Display error/warning tree at the top of the log if the runtime is `SAS`.
- Change error/warning font color within the log if the runtime is `SAS`.
- Added `web/src/containers/Studio/internal/components/log/logComponent.tsx`.
- Added `web/src/containers/Studio/internal/components/log/logTabWithIcons.tsx`.
- Added `web/src/utils/log.ts`.

Improve SAS log

---

web/src/containers/Studio/internal/components/log/logChunk.tsx
web/webpack.common.ts

- Css styles were loaded incorrectly.
- Log chunk has been collapsing when clicked on a body.
- Adjusted `web/webpack.common.ts`.
- Prevent onClick event propagation in `web/src/containers/Studio/internal/components/log/logChunk.tsx`.

Css issue fix

---

api/src/controllers/internal/Execution.ts
api/src/controllers/internal/Session.ts
web/src/components/snackbar.tsx
web/src/containers/Studio/internal/components/log/log.module.css
web/src/index.html

The response body can contain multiple logs and this is why log should always be wrapped from the beginning and the end.
- Improve response body.
- Wrapped log with log separator.

fix(log-separator): log separator should always wrap log

---

api/public/swagger.yaml
api/src/controllers/stp.ts
api/src/routes/api/stp.ts
api/src/utils/validation.ts

* swagger APIs didn't have the option to pass _debug as a query param
* update swagger docs to include _debug as optional query param fof\r GET stp/execute API endpoint

fix: add _debug as optional query param in swagger apis for  stp/execute

---

api/src/controllers/internal/createJSProgram.ts
api/src/utils/upload.ts

The aim is to avoid issues like this:

fix: enable embedded LFs in JS STP vars

---

api/package-lock.json
api/package.json
api/src/utils/setProcessVariables.ts

Closes #371 
- Fix MacOS executable env loading issue.
- Added `execPath` check to `setProcessVariables` func in `api/src/utils/setProcessVariables.ts` to provide a path to the `.env` file located in the same folder with the MacOS executable.
- Updated `dotenv` package.

fix(api): fixed env issue in MacOS executable

---

api/.env.example
api/public/swagger.yaml
api/src/controllers/code.ts
api/src/controllers/internal/Session.ts
api/src/controllers/stp.ts
api/src/controllers/user.ts
api/src/routes/api/code.ts
api/src/types/Session.ts
api/src/utils/upload.ts
api/src/utils/validation.ts

#373 
- Add `code/trigger` API endpoint.
- Added the `trigger` POST route to the code routes at `api/src/routes/api/code.ts`.
- Added the `triggerCode` method to the `CodeController` class at `api/src/controllers/code.ts`.
- Improved the `scheduleSessionDestroy` method of the `Session` class at `api/src/controllers/internal/Session.ts`.
- Extended `Session` type at `api/src/types/Session.ts`.
- Added `triggerCodeValidation` to `api/src/utils/validation.ts`.

feat(code): added code/trigger API endpoint

---

api/public/swagger.yaml
api/src/controllers/code.ts
api/src/controllers/stp.ts
api/src/routes/api/stp.ts
api/src/utils/validation.ts

Closes #373 
- Add `stp/trigger` API endpoint.
- Added `trigger` POST route to `api/src/routes/api/stp.ts`.
- Added `triggerProgramValidation` to `api/src/utils/validation.ts`.
- Added `triggerProgram` method to STPController class at `api/src/controllers/stp.ts`.

Issue 373 stp

---

api/public/swagger.yaml
api/src/controllers/stp.ts
api/src/routes/api/stp.ts

#373 
- Change the `stp/trigger` API endpoint to use query parameters.
- Adjusted the `trigger` route at `api/src/routes/api/stp.ts`.
- Adjusted the `triggerProgram` method of the `STPController` class at `api/src/controllers/stp.ts`.

feat(api): enabled query params in stp/trigger endpoint

---

.github/workflows/build.yml
api/src/controllers/internal/Session.ts
web/src/index.css

fix: extra bit of sleep for file recognition
