sasjs/server

.github/workflows/release.yml, .gitignore, README.md, api/package-lock.json, api/package.json, api/public/swagger.yaml, api/scripts/compileSysInit.ts, api/scripts/systemInit.sas, api/src/controllers/internal/Execution.ts, api/src/controllers/internal/Session.ts, api/src/controllers/stp.ts, api/src/routes/web/web.ts, api/src/utils/connectDB.ts, api/src/utils/file.ts
=> fix: Issue 9

api/src/app.ts, api/src/controllers/internal/Execution.ts, api/src/controllers/internal/Session.ts, api/src/types/Session.ts
Added sas9 server url to whitelist
Added check to session, boolean `consumed`
Session will not be deleted immediately, scheduler will do it.
=> Cors update

api/package-lock.json, api/package.json, api/scripts/systemInit.sas, package-lock.json, package.json
Enabling a set of useful core macros in each sasjs/server session
=> feat: default macros and bumping core

api/public/swagger.yaml, api/src/controllers/code.ts, api/src/controllers/drive.ts, api/src/controllers/internal/Execution.ts, api/src/controllers/stp.ts
=> fix(stp): return json for webout

api/public/swagger.yaml, api/src/controllers/drive.ts, api/src/routes/api/drive.ts, api/src/routes/api/spec/drive.spec.ts, api/src/utils/validation.ts, restClient/auth.rest, restClient/drive.rest, restClient/routes.rest, restClient/sample.sas, restClient/session.rest, restClient/users.rest
Can also provide file path in url for easy usage.
Updated specs + swagger docs:
=> Improve file upload

.gitignore, api/package.json, api/public/swagger.yaml, api/scripts/compileSysInit.ts, api/scripts/copySASjsCore.ts, api/src/controllers/drive.ts, api/src/controllers/internal/Execution.ts, api/src/controllers/internal/Session.ts, api/src/routes/api/drive.ts, api/src/utils/file.ts
=> fix: macros are available Sessions with SASAUTOS

api/package-lock.json, api/package.json, api/scripts/copySASjsCore.ts, api/src/app.ts, web/src/containers/Drive/main.tsx
=> fix: show content of get file api

web/src/containers/Drive/index.tsx, web/src/containers/Drive/main.tsx, web/src/containers/Drive/sideBar.tsx
* uplift state from the sidebar to parent component in drive container (it will help in removing the deleted file from directory tree)
* remove the deleted file from the directory tree
* directory tree is expanded by default at the root level
=> fix: remove deleted file from directory tree in sidebar of drive

README.md, api/.env.example, api/src/app.ts
=> feat(cors): whitelisting is configurable through .env variables

api/src/controllers/internal/Session.ts
=> fix: providing a PRINT destination during SAS invocation.

api/package-lock.json, web/package-lock.json, web/src/containers/Studio/index.tsx
Fixes #31 
Updated STUDIO log and webout section
=> fix: show contents as api responded

web/src/containers/Drive/index.tsx, web/src/containers/Drive/sideBar.tsx
* when drive page is refreshes expand the file tree in sidebar according to filePath query param in url
=> fix: improve user experience in sasjs drive

api/src/controllers/auth.ts, api/src/controllers/info.ts, api/src/routes/api/auth.ts, api/src/routes/api/spec/auth.spec.ts, api/src/utils/connectDB.ts
=> fix: fetch client from DB for each request

api/src/controllers/internal/Execution.ts
=> Execution controller more details in error message

api/public/swagger.yaml, api/src/controllers/user.ts, api/src/middlewares/verifyAdminIfNeeded.ts, api/src/routes/api/spec/user.spec.ts, api/src/routes/api/user.ts, api/src/utils/validation.ts
Close #188 
Added three new endpoints to get/patch/delete by username.
=> feat: new APIs added for GET|PATCH|DELETE of user by username

api/src/routes/appStream/appStreamHtml.ts, api/src/routes/appStream/style.ts
I did Some improvements to the design.
=> fix: appStream redesign

README.md, api/.env.example, api/src/controllers/internal/Execution.ts, api/src/controllers/internal/FileUploadController.ts, api/src/controllers/internal/Session.ts, api/src/controllers/internal/createJSProgram.ts, api/src/controllers/internal/processProgram.ts, api/src/server.ts, api/src/types/system/process.d.ts, api/src/utils/getCertificates.ts, api/src/utils/getDesktopFields.ts, api/src/utils/setProcessVariables.ts, api/src/utils/verifyEnvVariables.ts
HTTPS server can be configured through following configuration
- `key` ENV variable `PRIVATE_KEY`  required for HTTPS
- `cert` ENV variable changed `FULL_CHAIN` -> `CERT_CHAIN` required for HTTPS
- `ca` ENV variable introduced `CA_ROOT` optional for HTTPS
More details at : https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions
=> feat(certs): ENV variables updated and set CA Root for HTTPS server

api/public/swagger.yaml, api/src/controllers/web.ts, api/src/routes/web/web.ts, api/src/utils/getCertificates.ts, web/src/context/appContext.tsx
none
* Update /logout route to /SASLogon/logout to be more consistent like sas9 and viya
* CA certificates should be optional
* update `getCertificates` function to optionally return `ca`
=> Update logout route

api/package-lock.json, api/package.json, api/src/utils/getRunTimeAndFilePath.ts, api/tsoa.json
n/a
Improve descriptions
Updated json file
=> chore: update descriptions

web/src/components/header.tsx, web/src/containers/Studio/index.tsx
closes #216
closes #176 
* add documentation link under username dropdown menu
* add loading spinner while executing code in sasjs studio
* Added a new state variable `isRunning` that is responsible for showing loading spinner in sasjs studio
=> fix: Improve web UI

api/src/controllers/internal/Session.ts
=> fix: bank operator

api/src/routes/web/web.ts
#147 
Minimise security concerns
=> fix(security): missing cookie flags are added

web/src/components/filePathInputModal.tsx, web/src/components/header.tsx, web/src/components/nameInputModal.tsx, web/src/components/tree.tsx, web/src/containers/Studio/editor.tsx
closes #238
* improve user experience in the studio
* autofocus input field
* Select the default value 
* Submit on entering
* add action to the editor for showing diff editor (can be performed by right click and selecting option or `ctrl + d`)
* add command to the diff editor for moving back to the original editor on escape
=> fix: improve user experience in the studio

api/src/controllers/internal/Session.ts
#244 
Avoid unwanted popup windows on windows like this one
Added additional invocation options for SAS runtimes
=> fix: adding options to prevent unwanted windows on windows.  Closes #244

web/src/containers/Studio/editor.tsx, web/src/containers/Studio/index.tsx, web/src/containers/Studio/sideBar.tsx, web/src/index.css
closes #250 
* add margin to left and right on home page
* fix the tab list on the top of the studio page
=> fix(web): fix UI responsiveness

api/src/controllers/internal/Session.ts
#267 
Fix Allan's lack of JS skillz
Correct logic for windows / not windows adding SASINITIALFOLDER logic
=> fix: invalid JS logic

web/src/components/tree.tsx
closes #270
* add options for program launch and program launch with debug mode enabled from context menu
=> feat: add option for program launch in context menu

api/public/swagger.yaml, api/src/controllers/code.ts, api/src/controllers/stp.ts, api/tsoa.json
n/a
Updating API docs
Updated the descriptions and ran `npm run swagger` to regenerate the swagger.yml
=> chore(docs): updating API docs

web/src/containers/Studio/internal/helper.ts, web/src/containers/Studio/internal/hooks/useEditor.ts
=> fix(studio): inject program path to code before sending for execution

api/src/utils/getTokensFromDB.ts
closes #290
Improve code implementation for utility function `getTokensFromDB`
=> fix: in getTokensFromDB handle the scenario when tokens are expired

README.md, api/public/swagger.yaml, api/src/controllers/authConfig.ts, api/src/routes/api/authConfig.ts, web/src/containers/Settings/authConfig.tsx
n/a
Use of British English
Changed Synchronize to Synchronise
=> fix: spelling issues

api/package-lock.json, api/package.json, api/scripts/downloadMacros.ts, api/src/controllers/internal/Session.ts, api/src/utils/file.ts, api/src/utils/setupFolders.ts
closes #292
* Add the SAS_PACKAGES system macros to SASAUTOS
* Provision a directory for holding SAS_PACKAGES
* Inject a `filename packages "{directory}";` statement into the autoexec
* wrote a script for downloading macros
* updated `sasJSCoreMacros` path
* modified `getMacrosFolder` utility function
* added new `getPackagesFolder` utility function
=> feat: Enable SAS_PACKAGES in SASjs Server

api/.env.example, api/src/controllers/group.ts, api/src/controllers/user.ts, api/src/model/Group.ts, api/src/model/User.ts, api/src/utils/verifyEnvVariables.ts
* logic fixed for updating user created by external auth provider 
* remove internal from AuthProviderType
* replace AUTH_MECHANISM with AUTH_PROVIDERS
=> fix: ldap issues

web/src/containers/Studio/editor.tsx, web/src/containers/Studio/internal/hooks/useEditor.ts
=> fix: add action to editor ref for running code

api/public/swagger.yaml, api/src/controllers/auth.ts, api/src/controllers/client.ts, api/src/model/Client.ts, api/src/utils/generateAccessToken.ts, api/src/utils/generateRefreshToken.ts, api/src/utils/validation.ts
=> fix: change the expiration of access/refresh tokens from days to seconds

api/public/swagger.yaml, api/src/controllers/client.ts
Link any related issue(s) in this section.
What this PR intends to achieve.
What code changes have been made to achieve the intent.
=> fix: comments

api/public/swagger.yaml, api/src/app.ts, api/src/utils/createWeboutSasFile.ts, api/src/utils/index.ts, api/src/utils/setupFolders.ts
closes #318 
* add webout.sas to drive/sas/sasautos on startup with some specific content
* added a utility function that will be invoked from app.ts to create a webout.sas in drive/sas/sasautos
=> feat: on startup add webout.sas file in sasautos folder

api/src/controllers/internal/Execution.ts, api/src/controllers/internal/Session.ts, web/package-lock.json
=> fix: default response header fixed when debug is ON

api/package-lock.json, api/package.json, web/src/components/login.tsx
=> fix: show loading spinner on login screen while request is in process

api/src/controllers/auth.ts, api/src/controllers/user.ts, api/src/utils/seedDB.ts
=> fix: add user to all users group on user creation

web/src/index.tsx
=> fix(web): add proper base url in axios.defaults

web/src/containers/Studio/internal/components/runMenu.tsx
=> fix(web): add path to base in launch program url

web/src/containers/Studio/internal/components/runMenu.tsx
=> fix: add location.pathname to location.origin conditionally

api/public/swagger.yaml, api/src/controllers/client.ts, api/src/routes/api/client.ts, api/src/routes/api/spec/client.spec.ts
=> feat: add an api endpoint for admin to get list of client ids

api/src/controllers/internal/createSASProgram.ts
#274 #354
Removing print destination redirection (was causing errors in windows envs)
Removing print destination redirection (was causing errors in windows envs)
=> fix: removing print redirection pending full #274 fix
